services:
  mysql:
    image: mysql:8.0
    container_name: mysql_oauth
    restart: unless-stopped

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: asset3d_db
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "3306:3306"

    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
